---
- name: Configure BGP et les vrf
  hosts: routers
  gather_facts: false
  connection: network_cli
  remote_user: admin

  vars:
    cli:
      username: admin
      password: admin

  tasks:
  - name: config BGP
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{asn}}"
        bgp:
          router_id:
            address: "{{router_id}}"
        neighbors:
        - address: "{{address}}"
          remote_as: "{{asn}}"
          update_source: "{{update_source}}"
        - address: "{{neighbors_address}}"
          remote_as: "{{remote_as}}"
  - name: creation de la vrf
    cisco.ios.ios_vrf:
      name: Client_A
      description: vrf test
      rd: 1:100
      route_both:
        - 1:100
      state: present
  - name: assignation de la vrf
    cisco.ios.ios_vrf:
      name: Client_A
      interfaces:
        - "{{int_vrf}}"
      state: present
  - name: ip forwarding vrf sur PE1
    cisco.ios.ios_command:
      command:
        - "conf t"
        - "interface GigabitEthernet 1"
        - "vrf forwarding Client_A"
        - "no shutdown"
    when: ansible_hostname == 'PE1'
  - name: ip forwarding vrf sur PE2
    cisco.ios.ios_command:
      command:
        - "conf t"
        - "interface GigabitEthernet 2"
        - "vrf forwarding Client_A"
        - "no shutdown"
    when: ansible_hostname == 'PE2'
  - name: addresse ip des interfaces
    cisco.ios.ios_l3_interfaces:
      config:
        - name: "{{int_vrf}}"
          ipv4:
            - address: "{{ip}}"
          enabled: true
