---
- name: Configure BGP
  hosts: routers_CE
  gather_facts: false
  connection: network_cli
  remote_user: admin

  vars:
    cli:
      username: admin
      password: admin
  tasks:
  - name: config BGP CE
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{as_number}}"
        bgp:
          router_id:
            address: "{{router_id}}"
        neighbors:
        - address: "{{neighbors_address}}"
          remote_as: "{{remote_as}}"