---
- name: Creation d'une vrf
  hosts: routers
  gather_facts: false
  connection: network_cli
  remote_user: admin

  vars:
    cli:
      username: admin
      password: admin

  tasks:
  - name: creation de la vrf
    cisco.ios.ios_vrf:
      name: Client_A
      description: vrf test
      rd: 1:100
      route_both:
        - 1:100
      state: present