---
- name: Configuration des interfaces
  hosts: routers_mpls
  gather_facts: false
  connection: network_cli
  remote_user: admin

  vars:
    cli:
      username: admin
      password: admin
  
  tasks:
  - name: Config mtu
    cisco.ios.ios_interfaces:
      config:
        - name: "{{interface}}"
          mtu: 1550

  - name: verif mtu mpls
    cisco.ios.ios_interfaces:
        running_config: "{{ lookup('file', 'config.cfg') }}"
        state: parsed